
name: Continuous Integration

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']

jobs:
  scala-ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: run tests scala 2.13
        run: sbt ++2.13 test

      - name: run tests scala 3.6
        run: sbt ++3.6 test
